# Generated by Django 5.2.17 on 2026-08-17 12:31

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Stable short code, e.g. 'northwind'. Used in API responses.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Partner company",
                "verbose_name_plural": "Partner companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "rank",
                    models.PositiveIntegerField(
                        help_text="Ordering. Higher is more advanced. Tier gating compares ranks.",
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["rank"],
            },
        ),
        migrations.CreateModel(
            name="CoachGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "coach",
                    models.ForeignKey(
                        help_text="LMS user who coaches this group.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nelc_coached_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coach_groups",
                        to="nelc_certification.partnercompany",
                    ),
                ),
            ],
            options={
                "ordering": ["partner__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="LearnerRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "coach_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="A learner sits under at most one coach at a time.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members",
                        to="nelc_certification.coachgroup",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nelc_learner_record",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learner_records",
                        to="nelc_certification.partnercompany",
                    ),
                ),
                (
                    "tier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current tier. Null means not yet tiered, which gates them out of everything.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learner_records",
                        to="nelc_certification.tier",
                    ),
                ),
            ],
            options={
                "ordering": ["user__username"],
            },
        ),
        migrations.CreateModel(
            name="LearnerActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("course_enrollment_created", "Course enrollment created"),
                            ("step_completed", "Step completed"),
                            ("tier_changed", "Tier changed"),
                            ("coach_adjustment", "Coach adjustment"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                (
                    "course_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Course key string, e.g. 'course-v1:org+course+run'. Never a foreign key.",
                        max_length=255,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nelc_caused_activity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "learner_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity",
                        to="nelc_certification.learnerrecord",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Learner activity",
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["learner_record", "-occurred_at"],
                        name="nelc_activity_feed_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="coachgroup",
            constraint=models.UniqueConstraint(
                fields=("coach", "partner", "name"),
                name="unique_coach_group_per_partner",
            ),
        ),
        migrations.AddIndex(
            model_name="learnerrecord",
            index=models.Index(
                fields=["coach_group", "partner"], name="nelc_lr_group_partner_idx"
            ),
        ),
    ]
